# Site settings
title: Abhishek Jain
email: abhi2000@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Abhishek Jain's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jainabhishek79
github_username:  jabhishek

# Build settings
highlighter: rouge
